### ISSUE TITLE
scala version fail？

### ISSUE THREAD

**Issue by jinleileiking** [arnobroekhof/kafka-http-metrics-reporter#2] opened 2016-10-14 12:17 UTC
java.lang.NoSuchMethodError: scala.Predef$.ArrowAssoc

**Comment by sumitm-iiit** [comment] 2017-01-24 17:32
Any updates on the fix for this issue ?

**Comment by arnobroekhof** [comment] 2017-03-06 14:19
Unable to reproduce, can you please be more specific?

**Comment by arnobroekhof** [comment] 2017-03-06 20:35
Updated library to kafka 2.12 and version 0.10.2.0

**Closed as completed by arnobroekhof** 2017-03-06 20:35 UTC
